### ISSUE TITLE
Facebook fan pages

### ISSUE THREAD

**Issue by ntreadway** [Yeti-Media/friend-scan-me#26]
QR codes for fan pages.

As a user:
I should be able to create a QR for the facebook page[s] I admin.

**Comment by nsanta** [comment]
@pat @ntreadway 

On branch nsanta/GH26 the facebook page has been implemented.

We need to think which will be the flow in this case.

You can access to the qrcodes for each page that you admin simply requesting the /facebook_pages page.

Note: The navigation bar needs to be on a partial so can be organized

Let me know if you have questions.

**Comment by pat270** [comment]
Just a reminder, I get this error when I try and connect with Facebook.

NoMethodError in SessionsController#create 

Application Trace
app/models/user.rb:74:in `update_facebook'
app/models/user.rb:28:in`find_or_create_with_omniauth'
app/controllers/sessions_controller.rb:9:in `create'

Full Trace here: https://gist.github.com/817aadf25f40c634dab6
