### ISSUE TITLE
Add custom logos to QR codes

### ISSUE THREAD

**Issue by ntreadway** [Yeti-Media/friend-scan-me#27]
Thinking it would be cool it integrate pretty QR codes or something like it.

As a User:
I would like to the ability to add a custom image to my QR code.

**Comment by nsanta** [comment]
@ntreadway this issue implies build our own QRcode creator.

**Comment by nsanta** [comment]
http://rqr.rubyforge.org/

**Comment by ntreadway** [comment]
@nsanta  lets put this in the back log for now.
