### ISSUE TITLE
add the qr code scanner options for each mobile device.

### ISSUE THREAD

**Issue by nsanta** [Yeti-Media/friend-scan-me#47]
http://www.scanme.com/

@pat270  see the bottom of this page and create a bar with different options. Maybe we should add the qr code scanners on the qr codes home section.

**Comment by pat270** [comment]
scanme has their own qr code app called scan. The bar at the bottom are the devices that the scan app is on. Do you think we should still list qr code scanner options? If so which ones should we list?

**Comment by nsanta** [comment]
@pat270 i know that they have their own app. Just show one alternative of each mobile device (your choice). @ntreadway is building an app for iphone.
