### ISSUE TITLE
We need to modify the FB connect flow for the FB app center.

### ISSUE THREAD

**Issue by ntreadway** [Yeti-Media/friend-scan-me#57]
We need to modify the FB connect flow.
*Note: We also need to keep the old flow.

As a User:

I want to login to FSM via the FB app center
Then I should be logged in
and I should be able to view my QR code.

https://developers.facebook.com/docs/guides/appcenter/#websites

**Comment by nsanta** [comment]
I will work on this today

**Comment by nsanta** [comment]
@ntreadway http://www.facebook.com/appcenter/friendscanme?preview=1.

**Comment by ntreadway** [comment]
@nsanta Thanks! This a a big step forward to getting placement in the FB app center!
